import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "./animations.css";
import Navbar from "@/src/components/navbar/NavBar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // puoi modificare i pesi se vuoi
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <head>
        <link href='https://cdn.boxicons.com/fonts/basic/boxicons.min.css' rel='stylesheet' />
        <link href='https://cdn.boxicons.com/fonts/brands/boxicons-brands.min.css' rel='stylesheet' />
        <link href='https://cdn.boxicons.com/fonts/animations.min.css' rel='stylesheet' />
      </head>
      <body
        className={`${poppins.variable} antialiased light`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
